# -- provide a name in place of 'app-of-apps'
nameOverride: app-of-apps
# -- string to fully override `"app-of-apps.fullname"`
fullnameOverride: ""

project:
  # -- project name
  name: default
  # -- project description
  description: application that launches other applications
  # -- project organization
  organization: caerulescens
  # -- project environment: 'dev'
  environment: dev
  # -- project region: 'local'
  region: local
  # -- project cluster domain
  domain: caerulescens.test
  # -- project cluster platform: 'minikube'
  platform: minikube
  # -- project cluster profile: 'default'
  profile: default
  # -- project gitops repository
  repository: https://github.com/caerulescens/kustomizations.git
  # -- project gitops branch
  branch: feature/updating-charts

network:
  # -- network enable: 'true', 'false'
  enabled: true
  # -- network issuer: 'selfsigned'
  issuer: selfsigned

logs:
  # -- logs enable: 'true', 'false'
  enabled: true
  # -- logs level: 'trace', 'debug', 'info', 'warn', 'error', 'critical'
  level: info
  # -- logs format: 'json'
  format: json

metrics:
  # -- metrics enable: 'true', 'false'
  enabled: true

traces:
  # -- traces enable: 'true', 'false'
  enabled: true

applications:

  istio:
    # -- istio enable: 'true', 'false'
    enabled: true
    # -- istio version
    revision: 1.23.2
    base:
      # -- istio-base namespace
      namespace: istio-system
      wave: -220
    istiod:
      # -- istiod namespace
      namespace: istio-system
      wave: -210
    gateway:
      # -- gateway namespace
      namespace: istio-ingress
      wave: -200

  certManager:
    # -- cert-manager enable: 'true', 'false'
    enabled: true
    # -- cert-manager version
    revision: 1.16.0
    # -- cert-manager namespace
    namespace: cert-manager
    wave: -190

  kiali:
    # -- kiali enable: 'true', 'false'
    enabled: false
    # -- kiali version
    revision: 1.89.7
    # -- kiali namespace
    namespace: kiali-operator
    wave: -130

  argocd:
    # -- argocd enable: 'true', 'false'
    enabled: false
    # -- argocd version
    revision: 7.6.8
    # -- argocd namespace
    namespace: argocd
    wave: -120

  knative:
    # -- knative enable: 'true', 'false'
    enabled: false
    operator:
      # -- knative operator version
      version: 1.15.0
      # -- knative operator namespace
      namespace: knative-operator
      wave: -110
    serving:
      # -- knative serving version
      version: 1.15.0
      # -- knative serving namespace
      namespace: knative-serving
      wave: -100
    eventing:
      # -- knative eventing version
      version: 1.15.0
      # -- knative eventing namespace
      namespace: knative-eventing
      wave: -90

  lgtm:
    # -- lgtm enable: 'true', 'false'
    enabled: false
    # -- lgtm version
    revision: 2.1.0
    # -- lgtm namespace
    namespace: lgtm-distributed
    wave: -80

  rook:
    # -- rook enable: 'true', 'false'
    enabled: false
    # -- rook version
    revision: 1.15.3
    # -- rook namespace
    namespace: rook-ceph
    wave: -70

  promtail:
    # -- promtail enable: 'true', 'false'
    enabled: false
    # -- promtail version
    revision: 6.16.6
    # -- promtail namespace
    namespace: promtail
    wave: -50

  strimzi:
    # -- strimzi enable: 'true', 'false'
    enabled: false
    # -- strimzi version
    revision: 0.43.0
    # -- strimzi namesapce
    namespace: kafka
    wave: -30

  rabbitmq:
    # -- rabbitmq enable: 'true', 'false'
    enabled: false
    # -- rabbitmq version
    revision: 4.3.24
    # -- rabbitmq namespace
    namespace: rabbitmq
    wave: -20
