{{ if and .Values.applications.knative.enabled .Values.applications.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-eventing
  namespace: {{ .Values.applications.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.applications.knative.eventing.wave | quote }}
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.knative.eventing.namespace }}
  project: {{ .Values.project.name }}
  source:
    path: knative-eventing/{{ .Values.project.platform }}-{{ .Values.project.environment }}-{{ .Values.project.profile }}
    kustomize:
      namespace: {{ .Values.applications.knative.eventing.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
{{ end }}
